nelmio_api_doc:
    documentation:
        info:
            title: Op3ra
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!docs|_error) # Accepts routes under /api except /api/doc
